<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>io.github.yak33</groupId>
        <artifactId>smart-customs-platform-cloud</artifactId>
        <version>${revision}</version>
    </parent>
    
    <artifactId>smart-customs-support</artifactId>
    <packaging>pom</packaging>
    
    <name>smart-customs-support</name>
    <description>智慧关务平台 - 支撑代码模块</description>
    
    <modules>
        <module>smart-customs-common</module>
        <module>smart-customs-api</module>
    </modules>

</project>
